# Generated by Django 5.1.4 on 2025-01-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_servicecategory_special_offer_specialoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='service',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='services',
            field=models.ManyToManyField(related_name='special_offers', to='services.service'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='discount_percentage',
            field=models.FloatField(),
        ),
    ]
