# Generated by Django 5.1.4 on 2025-01-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
